import { Project } from '~/types'

export const projects: Project[] = [
  {
    key: 'oodikone',
    image: 'oodikone.png',
    name: 'Oodikone',
    duration: 'Jan 2024 - Present',
    description:
      'A full stack web application for analyzing university data | Authored by Toska, University of Helsinki',
    technologies: [
      'javascript',
      'typescript',
      'node',
      'postgres',
      'docker',
      'cypress',
      'react',
      'semantic',
    ],
    repository: 'UniversityOfHelsinkiCS/oodikone',
    readMore: 'https://toska.dev/projects/oodikone',
    featured: true,
  },
  {
    key: 'rauhala-io',
    image: 'rauhala-io.png',
    name: 'rauhala.io',
    duration: 'Jun 2024 - Jul 2024',
    description: 'A personal website showcasing my projects and skills',
    technologies: ['typescript', 'react', 'joy'],
    repository: 'rikurauhala/rikurauhala.github.io',
    readMore: 'https://rauhala.io',
    featured: false,
  },
  {
    key: 'insights',
    image: 'insights.png',
    name: 'Insights',
    duration: 'Apr 2024 - Jun 2024',
    description: 'An interactive web application for visualizing GitHub data',
    technologies: ['typescript', 'github', 'cypress', 'react', 'mui'],
    repository: 'rikurauhala/insights',
    featured: true,
  },
  {
    key: 'seminar-paper',
    image: 'seminar-paper.png',
    name: 'Seminar paper',
    duration: 'Jan 2024 - Apr 2024',
    description:
      'An academic seminar paper on the topic of implementing multi-factor authentication',
    technologies: ['latex'],
    repository: 'rikurauhala/seminar-paper',
    readMore: 'https://github.com/rikurauhala/seminar-paper/blob/main/report.pdf',
    featured: false,
  },
  {
    key: 'bsc-thesis',
    image: 'bsc-thesis.png',
    name: "Bachelor's thesis",
    duration: 'Aug 2023 - Dec 2023',
    description:
      "A bachelor's thesis in computer science on the topic of cracking cryptographic hashes of passwords",
    technologies: ['latex'],
    repository: 'rikurauhala/bsc-thesis',
    readMore: 'https://github.com/rikurauhala/bsc-thesis/blob/main/thesis.pdf',
    featured: true,
  },
  {
    key: 'hack-this',
    image: 'hack-this.png',
    name: 'Hack This',
    duration: 'Jul 2023 - Aug 2023',
    description: 'A full stack web application demonstrating common security vulnerabilities',
    technologies: ['typescript', 'node', 'sqlite', 'react', 'tailwind'],
    repository: 'rikurauhala/hack-this',
    featured: true,
  },
  {
    key: 'berry-picker-tracker',
    image: 'berry-picker-tracker.png',
    name: 'Berry Picker Tracker',
    duration: 'Jan 2023 - May 2023',
    description:
      'A mobile application for preventing berry pickers from getting lost in the forest | Authored by the Marjanpoimijat team',
    technologies: ['python', 'postgres', 'docker', 'typescript', 'reactnative'],
    repository: 'marjanpoimijat',
    readMore: 'https://marjanpoimijat.github.io',
    featured: true,
  },
  {
    key: '0b-is',
    image: '0b-is.png',
    name: '0b.is',
    duration: 'Dec 2022 - Feb 2023',
    description:
      'An intuitive web application for quickly converting numbers between different bases',
    technologies: ['typescript', 'react', 'mui'],
    repository: 'rikurauhala/0b.is',
    featured: true,
  },
  {
    key: 'you.github.io',
    image: 'you-github-io.png',
    name: 'you.github.io',
    duration: 'Jan 2022 - Dec 2022',
    description:
      'A portfolio website template for developers to showcase their projects and skills',
    technologies: ['typescript', 'github', 'react', 'mui'],
    repository: 'rikurauhala/you.github.io',
    featured: false,
  },
  {
    key: 'minitex',
    image: 'minitex.png',
    name: 'Minitex',
    duration: 'Nov 2022 - Dec 2022',
    description:
      'A command-line application for managing academic references | Authored by the Minitex team',
    technologies: ['python'],
    repository: 'rikurauhala/minitex',
    featured: false,
  },
  {
    key: 'rsa',
    image: 'rsa.png',
    name: 'RSA',
    duration: 'Sep 2022 - Oct 2022',
    description: 'An implementation of the RSA cryptosystem with a command-line interface',
    technologies: ['python'],
    repository: 'rikurauhala/rsa',
    featured: false,
  },
  {
    key: 'yesan',
    image: 'yesan.png',
    name: 'Yesan',
    duration: 'Mar 2022 - May 2022',
    description: 'A GUI desktop application for managing personal finances',
    technologies: ['python', 'sqlite'],
    repository: 'rikurauhala/yesan',
    featured: false,
  },
  {
    key: 'tj-bot',
    image: 'tj-bot.png',
    name: 'TJ-bot',
    duration: 'Jun 2021 - Sep 2021',
    description:
      'A Discord bot for reminding your friends in the Finnish military how many morning they have left',
    technologies: ['python', 'discord'],
    repository: 'rikurauhala/tj-bot',
    featured: false,
  },
  {
    key: 'film-review-app',
    image: 'film-review-app.png',
    name: 'Film Review App',
    duration: 'Mar 2021 - Jun 2021',
    description: 'A full stack web application for reading and writing film reviews',
    technologies: ['python', 'postgres', 'html', 'css'],
    repository: 'rikurauhala/film-review-app',
    featured: false,
  },
]
